# Generated by Django 3.1.10 on 2023-12-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_updb'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logindb',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='following',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
