# Generated by Django 3.1.10 on 2023-12-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20231229_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindb',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='logindb',
            name='following',
        ),
    ]
