# Generated by Django 3.1.10 on 2023-12-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20231229_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='image',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='password',
        ),
    ]
