# Generated by Django 3.1.10 on 2023-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_auto_20231229_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
