# Generated by Django 3.1.10 on 2023-12-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_follow_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('followers', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
