# Generated by Django 3.1.10 on 2023-12-31 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_auto_20231230_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='updb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
