# Generated by Django 3.1.10 on 2024-01-01 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_postm_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
