# Generated by Django 3.1.10 on 2024-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0014_logindb_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
