# Generated by Django 3.1.10 on 2024-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0015_auto_20240103_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
